version: '3.1'
services:
  ms-pedido-api:
    image: wolwer/ms-pedido-api
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:my-secret-pw@mongodb:27017/pedidos?authSource=admin
      SPRING_PROFILES_ACTIVE: hom

  ms-admin-api:
    image: wolwer/ms-admin-api
    ports:
      - "8081:8081"
    depends_on:
      - postgres-admin
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-admin:5432/admin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
      SPRING_PROFILES_ACTIVE: hom

  ms-cliente-api:
    image: wolwer/ms-cliente-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-cliente
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-cliente:5432/cliente
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
      SPRING_PROFILES_ACTIVE: hom

  postgres-cliente:
    image: postgres:latest
    container_name: postgres_cliente
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: cliente
    ports:
      - "5432:5432"
    volumes:
      - postgres_cliente_data:/var/lib/postgresql/data

  postgres-admin:
    image: postgres:latest
    container_name: postgres_admin
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_admin_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb_pedidos
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: my-secret-pw
      MONGO_INITDB_DATABASE: pedidos
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db/
      - /etc/timezone:/etc/timezone:ro

  mongo-express:
    image: mongo-express:latest
    container_name: mongodb_express_pedidos
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: my-secret-pw
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://mongo:my-secret-pw@mongo:27017/pedidos?authSource=admin
    ports:
      - "8070:8081"
    depends_on:
      - mongodb

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
    depends_on:
      - kafka
      - zookeeper

volumes:
  postgres_cliente_data:
  postgres_admin_data:
  mongodb_data:
